#!/bin/bash
feature_type_list=(Cnv Frag Griffin Arm)
input_size=(50 35 55 30)
for i in {0..4}
do
    python ./CNN_run.py ${feature_type_list[i]} ${input_size[i]} 200 1000 /mnt/binf/eric/Results_0704
done

